'''rc stands for reverse complement, not the city :)'''
def rc(dna):
    complement = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'}
    r_c = ''.join(complement[base] for base in reversed(dna))
    return r_c

dna = "GGATAGTGGAGATCTTTGTGTTGGGGAATCGGCGTGCTAGTTTTTGGATCTATCCTTGTCTAGCATGCTTCCTTGGTGGACGTGACGTGACGTTTAAACCGCGCTGCTGTGGCACCTCAGACACATGGGCTCAAAGGTTAGTTTGGGGATGCAAACCCCTATCCATGGGGGTCTACGCACCGAAAACCTCCTAGTAGAGTCTCGATAGAACGCGCAATGTCGAAGAAAATCACGGAGGACGGTAACAGACTAAGAATGCAATCCAAGAGCAAGAGCCTTATCTGGCCGAGTACTCTAACCATGGCTCTAAATGCTTTCCACTTGTAACCTGGACTAAAGCTAATGACCGCGGATTTAGTCTTCGTTGAACAAATCGGCTCTGTAGCTGTTTGTAACATTAGCTAGAAGTGTGCCACAAAAGTGAGAGCAGGATTTTACCACCCAGTCTCATGGACGCAGGCAATCCCCTCCATCTTGGCCGTGGCCCCGCCGCTGTGGCATGAATATGTCGTGCGGAAGCGAGTGCTCAGGAGTGTGGTAAGACTTGCGCATACGAGGTATCCGGTGTGATCGTCACTTATGCGGTCGCCGGCGCGGAGAATTTTGCAGGGGTGGCGCGGCCGCTCTTCTGGCCCTCCCCAACCGTCTGGTCGTTGCATCTCAAACGAGACGTCTAGGGATCAATTGGTGATCACATCATCACTCCTCAGCTACTAGTCGCAAGTACCAATCAGTGAGTTCGAACCATCGCAGTCCTAGCCAGTTCTACTGTTGTAATAACGCCTCGATGTACGCCGAGCACG"
revc = rc(dna)

print(revc)