def sub_loc(s, t):
    loc = []
    for i in range(len(s) - len(t) + 1):
        if s[i:i+len(t)] == t:
            loc.append(i + 1) 

    return loc

s = "AGCTGAACGAAAACAAATGAAAACAGAAAACAGAAAACAGGAAAACAGAAAACAGGAAAACAGAGTGGAGAAAACAAAAATGAAAACAGAAAACAGAAAACAAGGAAAACAGAAAACATGGAAAACACGTGACGAGAAAACAAAGAAAACAAGCTGAAAACAATGAAAACACCGCGCGGAAAACATATCCTCGGAAAACAGAAAACACAGCACATGAAAACATCAGAAAACATTAGAAAACAGGGAAAACAGAAAACAGAAAACAAGAAAACACGAAAACATTATGACCTCCGGGAAAACAGTGAGAAAACAGGAAAACATGAAAACAGAAAACAGAAAACAAGAAAACAGAAAACATAGAAAACAGTCAAACGAAAACAGGAAAACAGGCTACACGAAAACACGAATAAGAAAACAAGAAAACAAGCATCGAAAACAGAAAACATTGCCTAGAAAACAGAAAACAGGAAAACACTGAAAACAGGAAAACACGAAAACAGAGGAAAACAGCGAAAACAAATATTTATGAAAACATAGAAAACAGGAAAACATATCCCATATGAAAACATGAAAACAGAAAACATAGAAAACACCATTCTTTTGAAAACACGAAAACAAGAAAACAGAAAACAGCGAAAACAGAAAACATGGAAAACAGAAAACAGAAAACAAGAAAACAACAGAAAACAGAAAACAGAAAACAGGAAAACAGAAAACAGAAAACAGAAAACAGAAAACAATAGAAAACAGAAAACACTTGAAAACAGAAAACATCACGAAAACAGAAAACATTTAGGTGAAAACAGAAAACAGAGAAAACAATCGAAAACAGAAAACACGAAAACAGAAAACAGTGAACCTAATGAAAACAAGTGAAAACAAGGTCCTGGAAAACACGAAAACAACGAAAACACAAATGGGGAAAACAATCGAAAACACGAAAACATAGAAAACAGGAAAACAATAAACTG"
t = "GAAAACAGA"

result = sub_loc(s, t)

print(result)