def tran(s1, s2):
    transi = 0
    transv = 0

    for x, y in zip(s1, s2):
        if x != y:
            if (x, y) in [("A", "G"), ("G", "A"), ("C", "T"), ("T", "C")]:
                transi += 1
            else:
                transv += 1

    if transv == 0:
        return 0 #quella volta in cui a compsci prendemmo tutti un punto in meno perchè nessuno aveva considerato il caso :0... una ferita aperta </3
    else:
        return transi / transv

s1 = "CTAGAGGCGTCGATACAATGTTTTCCGTGAAAGAAGAGGTAGGGGATAAGCAGTGTTCCGAGAACGTGATCGCCAGTTCTCCCCAACCCGTGGGCTTCCAGGAACCACCGCAAGTTAGCCTCTGGAGAGGACATGAGGCCAACGTGCTTTTATGCTTGTAGTAGTCGCATGTATGGATGAAATCTCTGCCCCTGCTAGTAGCGCGGCAGCTCCGCATGCACTTCAAACACCTTTCCCAGCGAGAGTGAGCCAAGGATCGTAGGCTATCGATAGAGCCGACAGTTCATCTGGTTGACTGAAGCTATGTAGAACAGCTTTGGTTCGTTCTCTCGCTTCCTTAGTTAATTGACCATATAATCCTCAGATTGGACGCGTGGGACATTTCGCTGCGGAGGGGCCGTGATACAGGCCTGTCGAGAGGAATAGCGAGTAGCTATTGGCAGGGACCGTTAGTGTGCTACCCTACTCGGTTGCCAGTGATTCAAAATACTATCCTATTGCCTATAACAGCCCCCGTCATGTTTTGTTAACAGGGTCACCTTCATTAGCACCTGTAAACACCCCCGGTATACAACAGTCCTACCCGAAGGTCACTGGTTTGAGCTCACCACTAGTGTAGGAGGAGGATACTCGGCGGCGTCAATCAAATAATCTATAAAAGGGTGGCTACGCGGTACACCCCGCCGCGGAAAGACCTAAGGGCGTACAGAGCCCGCTACCACAAGGCCCGCCATCTCTGATGTAATCCTGTTGGTGAACTGCGGAATAAGTTGGGGCCCGTTAACGCAGGAAAACATCTATGCGGCGGTACAAGTATAATTATACAAGAGAGACGAAATGAAGTAAAACATCGATATGCTAATGCCGTGTCGGTTAGGATACGTCTCTCGTGATCATCGACCTGCAACATGGGCCTGCAGCCTTACTCATCCACCGCCTCTGGAACACTAAATCGTCGTATGGGTTTTTTTCGCGGTGGACGTG"
s2 = "CCAGTGGCGTCGGTGCGATGGCTTCTGAGAAATAAAAGATAGGGGACGAGCAGTGTTCTGAGGACGCGGTCACCAGCTTTCTTCCACCCATATGCTTCCGGGGGATACTGCAAGTGAGCCTGTAAATAAGAAATAGAACTAGTGAGCTTCGATGTTTGCATCGGTCGCATGCAAGGGCGAAAACTCCGCCCTTGATCGTAACACGTTGAATCGACATGAACTCCGAGCACCCCTCTCAGCGGGAGTTAACGAAAGACCCTAGACAACCGATACAGTCGATGGTTCATCCGGTTGACTGAAGGTGTTTAGGACAGTTCCGACCCGTTCTCCCGCTACCTTAGCTGACCAGCGGTATGATGCTCAGGTAGGACGCGTGGGGTACCTCGACGCGAAAACACTTTAATAACGAGCGGTTAAGAGGGATAGCGAGTAACTACTGTCAGGGATCGCCGGTGTACTACCCTAAATGGCTGCTAGGGATTCTGAGCACTATTCTTTTGCCATGAAGAGCCCGCTCTAAGTGTCAGTAACAGGGTCGGCTCCATTAGCACCTGTAAACGCCCCCCGTATGCGAGAGTCCCACCCACAGGCCGCTGACCCGAGGGCTCTTCTAGTGTAAGAGGTCGGCGCTTGGCGGCGCCGATAAAATAGGCTATGATAAGGTGACTACAGGGAATACCTCGTCAGGGAAAGATATAAGCGTGCGCAGAGCCGGCAACCATAAAGTCCGGCATCCTTGATGCAGTCCTATCGGCGGATTGCGTAATACGTCAGAGCCCGCTAATGCAAAGAAACATTTGTGTGGCGACGTAAATGTAATTACATTATGGAGTCAAAGTGAAATAGTATATTGATATGCGGGCGCGGTGACGGTTAGAATACAGTTATTGTGATAATGGACCTGGAACGTGACCCTTCAGCCTCACTCACCCGTCAACTTTGGAACACCGACTCGTCGTATCGGTTTCTTTAACGGTAGATTTG"
Tran = tran(s1, s2)
print(Tran)
